In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt





%matplotlib inline

In [2]:
pwd

'C:\\Users\\User1'

In [3]:
cd C:\Users\User1\OneDrive\Desktop\IBM Work\IBM Capstone Project for Crash Severity

C:\Users\User1\OneDrive\Desktop\IBM Work\IBM Capstone Project for Crash Severity


In [4]:
pwd

'C:\\Users\\User1\\OneDrive\\Desktop\\IBM Work\\IBM Capstone Project for Crash Severity'

In [58]:
crash_data=pd.read_csv("Data-Collisions.csv")
print("Data has been loaded")

Data has been loaded


c:\users\user1\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [59]:
crash_data.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      NaN  ...      Wet  Dark - Street Lights On   
2  Matched         Block      NaN  ...      Dry                 Daylight   
3  Matched         Block      NaN  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [60]:
crash_data.shape

(194673, 38)

In [61]:
crash_data.columns

Index(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO',
       'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
       'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC', 'COLLISIONTYPE',
       'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INCDATE',
       'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE', 'SDOT_COLDESC',
       'INATTENTIONIND', 'UNDERINFL', 'WEATHER', 'ROADCOND', 'LIGHTCOND',
       'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING', 'ST_COLCODE', 'ST_COLDESC',
       'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR'],
      dtype='object')

In [62]:
drop = ['OBJECTID', 'SEVERITYCODE.1', 'REPORTNO', 'INCKEY', 'COLDETKEY',
        'X', 'Y', 'STATUS','ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE',
        'EXCEPTRSNDESC', 'SEVERITYDESC', 'INCDATE', 'INCDTTM', 'JUNCTIONTYPE',
        'SDOT_COLCODE', 'SDOT_COLDESC', 'SDOTCOLNUM', 'ST_COLCODE', 'ST_COLDESC',
        'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR', 'COLLISIONTYPE', 'UNDERINFL']
crash_data.drop(drop, axis=1, inplace=True)

In [16]:
###crash_data.fillna('###', inplace=True)

In [63]:
crash_data.head()

SEVERITYCODE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT INATTENTIONIND  \
0             2            2         0            0         2            NaN   
1             1            2         0            0         2            NaN   
2             1            4         0            0         3            NaN   
3             1            3         0            0         3            NaN   
4             2            2         0            0         2            NaN   

    WEATHER ROADCOND                LIGHTCOND PEDROWNOTGRNT SPEEDING  
0  Overcast      Wet                 Daylight           NaN      NaN  
1   Raining      Wet  Dark - Street Lights On           NaN      NaN  
2  Overcast      Dry                 Daylight           NaN      NaN  
3     Clear      Dry                 Daylight           NaN      NaN  
4   Raining      Wet                 Daylight           NaN      NaN

In [64]:
crash_data.tail()

SEVERITYCODE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT  \
194668             2            3         0            0         2   
194669             1            2         0            0         2   
194670             2            3         0            0         2   
194671             2            2         0            1         1   
194672             1            2         0            0         2   

       INATTENTIONIND  WEATHER ROADCOND LIGHTCOND PEDROWNOTGRNT SPEEDING  
194668            NaN    Clear      Dry  Daylight           NaN      NaN  
194669              Y  Raining      Wet  Daylight           NaN      NaN  
194670            NaN    Clear      Dry  Daylight           NaN      NaN  
194671            NaN    Clear      Dry      Dusk           NaN      NaN  
194672            NaN    Clear      Wet  Daylight           NaN      NaN

In [65]:
crash_data[['SEVERITYCODE']].isnull()

SEVERITYCODE
0              False
1              False
2              False
3              False
4              False
...              ...
194668         False
194669         False
194670         False
194671         False
194672         False

[194673 rows x 1 columns]

In [66]:
crash_data=crash_data.fillna(0)

In [67]:
crash_data.head()

SEVERITYCODE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT INATTENTIONIND  \
0             2            2         0            0         2              0   
1             1            2         0            0         2              0   
2             1            4         0            0         3              0   
3             1            3         0            0         3              0   
4             2            2         0            0         2              0   

    WEATHER ROADCOND                LIGHTCOND PEDROWNOTGRNT SPEEDING  
0  Overcast      Wet                 Daylight             0        0  
1   Raining      Wet  Dark - Street Lights On             0        0  
2  Overcast      Dry                 Daylight             0        0  
3     Clear      Dry                 Daylight             0        0  
4   Raining      Wet                 Daylight             0        0

In [68]:
crash_data.replace(['N'], [0], inplace=True)
crash_data.replace(['Y'], [1], inplace=True)

In [69]:
crash_data.head()

SEVERITYCODE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT  INATTENTIONIND  \
0             2            2         0            0         2               0   
1             1            2         0            0         2               0   
2             1            4         0            0         3               0   
3             1            3         0            0         3               0   
4             2            2         0            0         2               0   

    WEATHER ROADCOND                LIGHTCOND  PEDROWNOTGRNT  SPEEDING  
0  Overcast      Wet                 Daylight              0         0  
1   Raining      Wet  Dark - Street Lights On              0         0  
2  Overcast      Dry                 Daylight              0         0  
3     Clear      Dry                 Daylight              0         0  
4   Raining      Wet                 Daylight              0         0

In [70]:
crash_data.shape

(194673, 11)

In [102]:
# Label encoding
crash_data["WEATHER"] = crash_data["WEATHER"].astype('category')
crash_data["ROADCOND"] = crash_data["ROADCOND"].astype('category')
crash_data["LIGHTCOND"] = crash_data["LIGHTCOND"].astype('category')

# Assign variable to new column for analysis
crash_data["WEATHER_CAT"] = crash_data["WEATHER"].cat.codes
crash_data["ROADCOND_CAT"] = crash_data["ROADCOND"].cat.codes
crash_data["LIGHTCOND_CAT"] = crash_data["LIGHTCOND"].cat.codes

In [103]:
crash_data.head()

SEVERITYCODE  PERSONCOUNT  PEDCOUNT  PEDCYLCOUNT  VEHCOUNT  INATTENTIONIND  \
0             2            2         0            0         2               0   
1             1            2         0            0         2               0   
2             1            4         0            0         3               0   
3             1            3         0            0         3               0   
4             2            2         0            0         2               0   

    WEATHER ROADCOND                LIGHTCOND  PEDROWNOTGRNT  SPEEDING  \
0  Overcast      Wet                 Daylight              0         0   
1   Raining      Wet  Dark - Street Lights On              0         0   
2  Overcast      Dry                 Daylight              0         0   
3     Clear      Dry                 Daylight              0         0   
4   Raining      Wet                 Daylight              0         0   

   WEATHER_CAT  ROADCOND_CAT  LIGHTCOND_CAT  
0            5             9              6  
1            7             9              3  
2            5             1              6  
3            2             1              6  
4            7             9              6

In [93]:
crash_data.shape

(194673, 14)

In [74]:
crash_data.dtypes

SEVERITYCODE         int64
PERSONCOUNT          int64
PEDCOUNT             int64
PEDCYLCOUNT          int64
VEHCOUNT             int64
INATTENTIONIND       int64
WEATHER           category
ROADCOND          category
LIGHTCOND         category
PEDROWNOTGRNT        int64
SPEEDING             int64
WEATHER_CAT           int8
ROADCOND_CAT          int8
LIGHTCOND_CAT         int8
dtype: object

In [94]:
crash_data['SEVERITYCODE'].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

In [76]:
crash_data['PERSONCOUNT'].value_counts()

2     114231
3      35553
4      14660
1      13154
5       6584
0       5544
6       2702
7       1131
8        533
9        216
10       128
11        56
12        33
13        21
14        19
15        11
17        11
16         8
44         6
18         6
20         6
25         6
19         5
26         4
22         4
27         3
28         3
29         3
47         3
32         3
34         3
37         3
23         2
21         2
24         2
30         2
36         2
57         1
31         1
35         1
39         1
41         1
43         1
48         1
53         1
54         1
81         1
Name: PERSONCOUNT, dtype: int64

In [77]:
crash_data['PEDCOUNT'].value_counts()

0    187734
1      6685
2       226
3        22
4         4
6         1
5         1
Name: PEDCOUNT, dtype: int64

In [78]:
crash_data['WEATHER_CAT'].value_counts()

2     111135
7      33145
5      27714
11     15091
0       5081
10       907
4        832
3        569
9        113
1         56
8         25
6          5
Name: WEATHER_CAT, dtype: int64

In [95]:
!pip3 install scikit-learn scipy matplotlib

In [96]:
from sklearn.utils import resample

In [128]:
# Seperate majority and minority classes
crash_data_majority = crash_data[crash_data.SEVERITYCODE==1]
crash_data_minority = crash_data[crash_data.SEVERITYCODE==2]

#Downsample majority class
crash_data_majority_downsampled = resample(crash_data_majority,
                                        replace=False,
                                        n_samples=58188,
                                        random_state=123)

# Combine minority class with downsampled majority class
crash_data_balanced = pd.concat([crash_data_majority_downsampled, crash_data_minority])

# Display new class counts
crash_data_balanced.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [150]:
###Effort to Build a Random Tree
###list_for_X = ['PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INATTENTIONIND'
              'PEDROWNOTGRNT', 'SPEEDING', 'WEATHER_CAT', 'ROADCOND_CAT',
              'LIGHTCOND_CAT']

In [144]:
#X = crash_data.iloc[:, 1:13].values

In [99]:
#Y_hat = crash_data.iloc[:, 0].values

In [145]:
#from sklearn.ensemble import RandomForestRegressor

In [126]:
#regressor = RandomForestRegressor(n_estimators=50, random_state=0)
#regressor.fit(X, Y_hat)  ###end of effort to build random tree

In [156]:
###Initialize, define X and Y
import numpy as np

x = np.asarray(crash_data_balanced[['PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 'INATTENTIONIND',
                                    'PEDROWNOTGRNT', 'SPEEDING', 'WEATHER_CAT', 'ROADCOND_CAT',
                                    'LIGHTCOND_CAT']])
x[0:5]

array([[ 2,  0,  0,  2,  0,  0,  0,  7,  9,  3],
       [ 2,  0,  0,  2,  0,  0,  0,  2,  1,  6],
       [ 2,  0,  0,  2,  0,  0,  0, 11,  8,  9],
       [ 2,  0,  0,  2,  0,  0,  0,  2,  1,  6],
       [ 3,  0,  0,  2,  0,  0,  0,  2,  1,  6]], dtype=int64)

In [154]:
y_hat = np.asarray(crash_data_balanced['SEVERITYCODE'])
y_hat [0:5]

#initilization of X and Y finished

array([1, 1, 1, 1, 1], dtype=int64)

In [167]:
###Normalize data set

from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x)
x[0:14]

array([[-0.36911465, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155,  1.15236718,  1.52797946, -1.21648407],
       [-0.36911465, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155, -0.67488   , -0.67084969,  0.42978835],
       [-0.36911465, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155,  2.61416492,  1.25312582,  2.07606076],
       [-0.36911465, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155, -0.67488   , -0.67084969,  0.42978835],
       [ 0.33549933, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155, -0.67488   , -0.67084969,  0.42978835],
       [ 1.04011332, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155, -0.67488   , -0.67084969,  0.42978835],
       [-0.36911465, -0.23764842, -0.21264054,  0.14288121, -0.43697754,
        -0.1981104 , -0.23274155, -0.67488   

In [170]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y_hat, test_size=0.3, random_state=4)
print ('Train set:', x_train.shape,  y_train.shape)
print ('Test set:', x_test.shape,  y_test.shape)

Train set: (81463, 10) (81463,)
Test set: (34913, 10) (34913,)


In [158]:
from sklearn.ensemble import RandomForestRegressor

In [184]:
regressor = RandomForestRegressor(n_estimators=50, random_state=0)
regressor
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)


print (y_pred [0:14])
print (y_test [0:14])

[1.95196747 1.58346157 1.04264104 1.03720496 1.38943188 1.69475624
 1.60499926 1.45169287 1.57971153 1.03652714 2.         1.57971153
 1.36519945 1.57971153]
[2 2 1 1 1 2 1 1 1 1 2 1 1 1]


In [2]:
###import graphviz

##dot_data = export_graphviz(regressor,
                            ##filled=True, 
                            ##rounded=True,
                            ##out_file=None,
                            ##feature_names=list(x))  

##graph=graph_from_dot_data(dot_data)

##graph.write_png('tree.png')

##from IPython.display import Image
##mage('tree.png', width=1000)

In [185]:
#evaluation procedure
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

kfold = KFold(n_splits=10, shuffle=True, random_state=100)

#cross validation
score1 = cross_val_score(regressor, x, y_hat, cv=kfold)
print("mean accuracy %.2f%% (standard deviation %.2f%%)" % (score1.mean()*100, score1.std()*100))
#The results are summarized as both the mean and standard deviation of the model accuracy on the dataset.

mean accuracy 16.62% (standard deviation 0.49%)


In [ ]:
# Building the KNN Model
from sklearn import neighbors

cls = neighbors.KNeighborsClassifier()
cls.fit(x_train, y_train)
accuracy =cls.score(x_train, y_train)
print(accuracy)

k_hat_pred = cls.predict(x_test)
print(k_hat_pred)



In [192]:
#Train Model & Predict  
#nbgh = kn(n_neighbors = k).fit(x_train,y_train)
#nbgh

#k_hat_pred = nbgh.predict(x_test)
#K_hat_pred [0:14]

In [195]:
# Building the LR Model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=6, solver='liblinear')

In [198]:
##training and prediction for Linear Regression model
LRyhat = LR.predict(x_test)
LRyhat

array([2, 2, 1, ..., 1, 1, 2], dtype=int64)

In [200]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob

array([[0.0602781 , 0.9397219 ],
       [0.45719898, 0.54280102],
       [0.74706017, 0.25293983],
       ...,
       [0.57796883, 0.42203117],
       [0.51134532, 0.48865468],
       [0.04192822, 0.95807178]])

In [202]:
#Evaluations
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [ ]:
##f1_score(y_test, Kyhat, average='macro') ##for the N-neighbors 

In [204]:
yhat_prob = LR.predict_proba(x_test)
log_loss(y_test, yhat_prob)   ##Log Loss for Linear Regression

0.611560802481553

In [193]:
# Decision Tree Classifier
##from sklearn.tree import DecisionTreeClassifier
##crash_data_tree = DecisionTreeClassifier(criterion="entropy", max_depth = 7)
##crash_data_tree
##crash_data_tree.fit(X_train,y_train)  ###This tree sample is not in use